# This is the configuration for Travis CI, a free github-integrated service that runs this script for each pull request (if configured)

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# provides gcc, clang, make, scons, cmake
language: c++

# alternatives: gcc, clang, or both (as yaml list)
compiler: gcc

addons:
  apt:
    packages:
      - libbz2-dev
      - python3

before_install:
  # Don't touch source code directory
  - cd ..
  - wget https://github.com/y-256/libdivsufsort/archive/2.0.1.tar.gz -O /tmp/libdivsufsort.tar.gz
  - tar xzf /tmp/libdivsufsort.tar.gz

  - wget https://cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.tar.gz -O /tmp/cmake.tar.gz
  - tar xzf /tmp/cmake.tar.gz
  - export PATH=`pwd`/cmake-3.1.3-Linux-x86_64/bin/:${PATH}

install:
 - mkdir libdivsufsort-build libdivsufsort-install
 - export LIBDIVSUFSORT_INSTALL_PREFIX=`pwd`/libdivsufsort-install
 - cd libdivsufsort-build
 - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DUSE_OPENMP:BOOL=ON -DBUILD_DIVSUFSORT64:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=${LIBDIVSUFSORT_INSTALL_PREFIX} ../libdivsufsort-2.0.1
 - make -j4 && make install
 - cd ..

script:
 - mkdir andiff-build
 - cd andiff-build
 - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DLIBDIVSUFSORT_PREFIX:PATH=${LIBDIVSUFSORT_INSTALL_PREFIX} ../andiff
 - make
 - ctest -V

notifications:
  email: false
